# .github/workflows/execute-helmfile-apply.yml
name: Execute Helmfile Apply

on:
  workflow_call:
    inputs:

      environment:
        description: 'Target environment for helmfile'
        required: false
        type: string
        default: 'staging'
      gke_cluster_name:
        description: 'Name of the target GKE Cluster'
        required: true
        type: string
      gke_cluster_location:
        description: 'Location of the target GKE Cluster (e.g., us-central1)'
        required: true
        type: string
    secrets:
      GCP_SA_KEY:
        description: 'Google Cloud Service Account Key (JSON format)'
        required: true
      GH_TOKEN:
        description: 'GitHub token to checkout the private manifests repository'
        required: true

jobs:
  helmfile-apply:
    runs-on: ubuntu-latest
    
    steps:
      - name: 🚚 Checkout k8s-manifests repository
        uses: actions/checkout@v4
        with:
          repository: EcommerceDevops/k8s-manifests
          token: ${{ secrets.GH_TOKEN }}

      - name: 🔑 Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: ☸️ Setup GKE Kubeconfig
        uses: google-github-actions/get-gke-credentials@v2
        with:
          # --- VALORES AHORA GENÉRICOS ---
          cluster_name: ${{ inputs.gke_cluster_name }}
          location: ${{ inputs.gke_cluster_location }}

      - name: ⚙️ Setup Helm and Helmfile
        run: |
          echo "Installing Helm-diff plugin..."
          helm plugin install https://github.com/databus23/helm-diff

          echo "Installing Helmfile v1.1.0..."
          wget https://github.com/helmfile/helmfile/releases/download/v1.1.0/helmfile_1.1.0_linux_amd64.tar.gz
          tar -zxvf helmfile_1.1.0_linux_amd64.tar.gz
          sudo mv helmfile /usr/local/bin/helmfile
          helmfile --version

      - name: 🚀 Run Helmfile Sync for a specific service
        run: |
          helmfile -e ${{ inputs.environment }} apply